### ISSUE TITLE
Fails on Mac OS X 10.10.3 (Yosemite) with vanilla ruby

### ISSUE THREAD

**Issue by herzbube** [cowboy/ed-rare-trade-route-generator#7]
Here's the output when I run the script on my Mac OS X 10.10.3 (Yosemite) box, right after cloning the project:

```
$ ./generate-routes.rb 
Downloading spreadsheet to "ED_RareGoods_SystemsDistance - CURRENT.csv"...done
Parsing CSV data..../generate-routes.rb:106:in `block in <main>': undefined method `match' for nil:NilClass (NoMethodError)
    from ./generate-routes.rb:104:in `each'
    from ./generate-routes.rb:104:in `<main>'
```

And here the ruby version:

```
$ which ruby
/usr/bin/ruby
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

I don't know if that makes a difference, but I also have Homebrew installed on the machine.

I could probably figure this out myself if I took the time to learn a bit of ruby, but I haven't started my ED trading career in earnest yet, so my motivation is rather low at the moment. Let me do a bit of exploring first (I just got me a nicely outfitted Asp), and if there's no fix in a couple of weeks I'll try to provide one myself :-)

**Comment by nubbthedestroyer** [comment]
Confirmed that this occurs crossplatform in Ubuntu as well.

**Comment by nubbthedestroyer** [comment]
OK, figured out how to get this working.  The $csv_url and $source_sheet_url variables need to be updated.  If you follow those links you'll actually see the new link in that sheet.  Swap out these two variables with these values:

```
$source_sheet_url = 'https://docs.google.com/spreadsheets/d/17Zv55yEjVdHrNzkH7BPnTCtXRs8GDHqchYjo9Svkyh4/edit#gid=0'
$csv_url = 'https://docs.google.com/feeds/download/spreadsheets/Export?key=17Zv55yEjVdHrNzkH7BPnTCtXRs8GDHqchYjo9Svkyh4&exportFormat=csv&gid=0'
```
